version: "3"
services:
  db:
    image: postgres:bullseye
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo-usuarios
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres-db:
    external: true
